#logging.level.org.h2.server: DEBUG
# Database
#spring.datasource.url=jdbc:postgresql://ec2-107-21-109-15.compute-1.amazonaws.com:5432/dbrs3m1j5asp0t?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
#spring.datasource.username=lfpgcxojkznnnt
#spring.datasource.password=a98c7e0d46e07b9bd7b7e90b4e29b5096825bc2c2539744c7e34264b3cfe50a9
#spring.jpa.hibernate.ddl-auto=create-drop
#hibernate.temp.use_jdbc_metadata_defaults=false
#
#
#hibernate.hbm2ddl.auto=update

---
spring:
    profiles: development
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      datasource:
          url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:

---
spring:
    profiles: production
    jpa:
      hibernate:
        ddl-auto: create-drop
    properties:
      datasource:
          url: jdbc:postgres://rruakjnfmekpqq:b86b72630d144ffba52c3f4d852a91590750b8ba2f53925ce960f55397b4f283@ec2-23-21-197-231.compute-1.amazonaws.com:5432/d23djndovdrofk
          username: rruakjnfmekpqq
          password: b86b72630d144ffba52c3f4d852a91590750b8ba2f53925ce960f55397b4f283
